### ISSUE TITLE
JPEGmini gets stuck at "Go to Folder:" (Sierra)

### ISSUE THREAD

**Issue by maxwellhibbert** [JamieMason/ImageOptim-CLI#129]
imageOptim 1.14.8
JPEGmini Pro 1.9.8
macOS 10.12

JPEGmini is getting stuck on the file open dialogue with a input titled "Go to folder:" which has my user path inside. Then the script keeps going and tries ImageOptim.

I also get the same problem with grunt-imageoptim. I've not used ImageOptim-CLI or grunt-imageoptim in quite a while and not since updating to Sierra, so not sure if the new OS creates problems or not..

I've also tried with the normal version of JPEGmini with the same result.

**Comment by JamieMason** [comment]
Thanks @maxwellhibbert, 
I'm not on Sierra just yet but will pick this up in the next few weeks.

**Comment by moerphie** [comment]
+1 
same issue here. hope you can fix it soon, @JamieMason. :)

**Comment by JamieMason** [comment]
I'm still not on Sierra but here is some information about the problem incase someone is able to help out before I can.

1. The affected code I think will be [these lines](https://github.com/JamieMason/ImageOptim-CLI/blob/master/bin/imageOptimAppleScriptLib#L114-L121).
1. I don't know for sure but my guess is that in Sierra the path `text field 1 of sheet 1 of sheet 1 of window 1` could be different to the older versions of OS X.
1. There's an App called [UI Browser](http://pfiddlesoft.com/uibrowser/) which lets you click on bits of the OSX UI and inspect them, a little bit like the Elements panel of Chrome DevTools. Using this on Sierra will help confirm what the correct path to use should be.

**Comment by maxwellhibbert** [comment]
You're a champion!
Will this update make it to the grunt version eventually?

**Comment by JamieMason** [comment]
Thanks goes to @stefancrain for sorting this. I've just released 1.4.3 of grunt-imageoptim.

**Comment by Anthony-Reboul** [comment]
I still have the same issue with imageoptim-cli 1.14.9. My jpegmini pro version is 1.9.8 and I'm running on masOS Sierra.

Does anyone else have the same problem with 1.14.9 version ?
