### ISSUE TITLE
Can't remove temp folders after imageoptim runs

### ISSUE THREAD

**Issue by jhebb** [JamieMason/ImageOptim-CLI#96]
Hi, I'm getting the following errors every time the script is run:

rm: /var/folders/mn/mn5ycnzx7h90rsbmk7sypskm0000gn/T//imageoptim-cli/png/Users/username: Permission denied
rm: /var/folders/mn/mn5ycnzx7h90rsbmk7sypskm0000gn/T//imageoptim-cli/png/Users: Directory not empty
rm: /var/folders/mn/mn5ycnzx7h90rsbmk7sypskm0000gn/T//imageoptim-cli/png: Directory not empty
rm: /var/folders/mn/mn5ycnzx7h90rsbmk7sypskm0000gn/T//imageoptim-cli: Directory not empty

If I sudo rm -r the imageoptim folder, i just get the same error next time I run the script. Anything I can try to prevent it?

imageoptim-cli version 1.11.4

**Comment by JamieMason** [comment]
Sorry for the delay @jhebb. I get this issue myself and plan to fix it, but so far I'm not sure how to fix it.

**Comment by paultreny** [comment]
I get this same error, both in 1.11.4, but also in 1.11.6

:-/

**Comment by JamieMason** [comment]
This should be fixed in imageoptim-cli@1.14.8 by the fix for #87.

**Comment by jhebb** [comment]
@JamieMason I upgraded to 1.14.8 but still get this error - seems to be specifically when I run it on files on my desktop. Running it elsewhere works great.

**Comment by JamieMason** [comment]
@jhebb could you experiment and see if it only happens in that dir with particular flags set? Or if it just happens at all times when run from there?

**Comment by jhebb** [comment]
Different flags don't seem to matter. I tried:

find *.jpg | imageoptim -j -q
find *.jpg | imageoptim -j
find *.jpg | imageoptim
find *.jpg | imageoptim -q
imageoptim -d ~/Desktop
imageoptim -j -q -d ~/Desktop
etc

**Comment by jhebb** [comment]
Not a big deal for me, everything still runs fine and works.

**Comment by JamieMason** [comment]
OK thanks. Will leave this closed
